export let TRIPS = [
  {
    id: 1,
    name: "Copacabana Beach",
    date:'26 FEB 2019',
    price_adult: 60,
    price_child: 30,
    time: "12h",
    free_cancellation: 1,
    electric_voucher: 1,
    sub_name: "English Commentary Tour",
    thumb: "assets/img/trip/thumb/trip_1.jpg",
    description: "test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test vv",
    location: "Woohoo",
    images: [
      "assets/img/trip/thumb/trip_5.jpg",
      "assets/img/trip/thumb/trip_6.jpg",
      "assets/img/trip/thumb/trip_7.jpg",
      "assets/img/trip/thumb/trip_8.jpg",
    ],
    highlights: [
      "Numerous kiosks",
      "First in a string of Atlantic Ocean-facing beaches",
      "Sand is flanked by mountains in the background",
      "Swing in the turquoise waters",
      "Water Sports",
    ]
  },
  {
    id: 2,
    name: "Christ the Redeemer",
    date:'26 FEB 2019',
    price_adult: 90,
    price_child: 45,
    time: "4h",
    free_cancellation: 1,
    electric_voucher: 1,
    sub_name: "English Commentary Tour",
    thumb: "assets/img/trip/thumb/trip_2.jpg",
    description: "test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test vv",
    location: "Woohoo",
    images: [],
    highlights: []
  },
  {
    id: 3,
    name: "Ipiranga Museum",
    date:'26 FEB 2019',
    price_adult: 30,
    price_child: 15,
    time: "6h",
    free_cancellation: 1,
    electric_voucher: 1,
    sub_name: "English Commentary Tour",
    thumb: "assets/img/trip/thumb/trip_3.jpg",
    description: "test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test vv",
    location: "São Paulo, Brazil",
    images: [],
    highlights: []
  },
  {
    id: 4,
    name: "Fernando de Noronha",
    date:'26 FEB 2019',
    price_adult: 500,
    price_child: 250,
    time: "24h",
    free_cancellation: 1,
    electric_voucher: 1,
    sub_name: "English Commentary Tour",
    thumb: "assets/img/trip/thumb/trip_4.jpg",
    description: "test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test test vv",
    location: "Fernando de Noronha, Brazil",
    images: [],
    highlights: []
  }
]
